name: deploy.yml
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write #브랜치 접근권한
      packages: write #docker iamge repository접근권한

    steps:
      - name: Branch check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branch Master to Operation
        run: |
          git config --global user.name "deploy-manager"
          git config --global user.email "wuwang8484@gmail.com"
          git checkout operation || git checkout -b operation
          git reset --hard master
          git push origin operation --force

      - name: Authenticate GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push to GHCR
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWER/galaxy-archive-ai:latest .
          docker push ghcr.io/$REPO_LOWER/galaxy-archive-ai:latest

      - name: Copy docker application composes
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.ai.yml"
          target: "~/galaxyarchive"
          overwrite: true

      - name: Deploy to Operation Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            cd ~/galaxyarchive

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker compose -f docker-compose.ai.yml pull
            docker compose -f docker-compose.ai.yml up -d
            
            docker image prune -f